removing mentioning codecept.json config file
Codeception/CodeceptJS pull request #3410
Opened 2022-09-15 08:36 UTC by PeterNgTr

## Type of change
- [x] :clipboard: Documentation changes/updates

## Checklist:
- [x] Documentation has been added (Run `npm run docs`)
- [x] Local tests are passed (Run `npm test`)

2022-09-16 07:59 UTC, Arhell approved these changes

2022-09-25 19:51 UTC, DavertMik requested changes

2022-09-25 19:51 UTC, DavertMik commented on docs/commands.md
> +npx codeceptjs run --config path/to/codecept.js
if so please name it `codecept.conf.js` as it is default now

2022-10-05 11:02 UTC, DavertMik approved these changes

2022-10-05 11:02 UTC, DavertMik commented on docs/changelog.md
> +  // contents of codecept.js
```suggestion
  // contents of codecept.conf.js
```

2022-10-05 11:02 UTC, merged