improve gpo command
Codeception/CodeceptJS pull request #3411
Opened 2022-09-15 13:44 UTC by kobenguyent

## Motivation/Description of the PR
![Screen Shot 2022-09-15 at 2 13 41 PM](https://user-images.githubusercontent.com/7845001/190419597-b4a72309-f651-458d-836d-a6d9a7c9b8f6.png)

## Checklist:
- [x] Lint checking (Run `npm run lint`)
- [x] Local tests are passed (Run `npm test`)

2022-09-16 07:59 UTC, Arhell approved these changes

2022-09-25 19:55 UTC, DavertMik requested changes

2022-09-25 19:55 UTC, DavertMik commented on lib/command/generate.js
> +      message: `Do you plan to write ${kind} object in TypeScript?`,
we shell not ask this but guess from a config extension
if it is `codecept.conf.ts` then it should be `ts` extension

2022-10-05 10:52 UTC, DavertMik approved these changes

2022-10-05 11:00 UTC, merged