Typo fix for waitForTimeout in Webdriver config
Codeception/CodeceptJS pull request #3442
Opened 2022-10-10 11:49 UTC by himanshuapril1

## Motivation/Description of the PR
- Currently there is a typo in regards to Webdriver configuration where `waitforTimeout` is quoted as `waitForTimeout` with caps `F`. However as per [Webdriver documentation](https://webdriver.io/docs/timeouts/#waitfor-timeout) it should be small `f`.
> WebdriverIO provides multiple commands to wait on elements to reach a certain state (e.g. enabled, visible, existing). These commands take a selector argument and a timeout number, which determines how long the instance should wait for that element to reach the state. The `waitforTimeout` option allows you to set the global timeout for all `waitFor*` commands, so you don't need to set the same timeout over and over again. (**Note the lowercase f!**)

Applicable helpers:

- [x] WebDriver
- [ ] Puppeteer
- [ ] Nightmare
- [ ] REST
- [ ] FileHelper
- [ ] Appium
- [ ] Protractor
- [ ] TestCafe
- [ ] Playwright

Applicable plugins:

- [ ] allure
- [ ] autoDelay
- [ ] autoLogin
- [ ] customLocator
- [ ] pauseOnFail
- [ ] coverage
- [ ] retryFailedStep
- [ ] screenshotOnFail
- [ ] selenoid
- [ ] stepByStepReport
- [ ] stepTimeout
- [ ] wdio
- [ ] subtitles

## Type of change

- [ ] :fire: Breaking changes
- [ ] :rocket: New functionality
- [x] :bug: Bug fix
- [x] :clipboard: Documentation changes/updates
- [ ] :hotsprings: Hot fix
- [ ] :hammer: Markdown files fix - not related to source code
- [ ] :nail_care: Polish code

## Checklist:

- [x] Tests have been added
- [x] Documentation has been added (Run `npm run docs`)
- [x] Lint checking (Run `npm run lint`)
- [x] Local tests are passed (Run `npm test`)

2022-10-13 07:03 UTC, Arhell reviewed
@DavertMik

2022-10-13 07:38 UTC, PeterNgTr approved these changes

2022-10-24 10:17 UTC, DavertMik requested changes
This can be a breaking change.

Can we just add alias so `waitForTimeout` to be the same as `waitforTimeout` ?

Personally I would prefer to use waitForTimeout as it seems more native to me and less confusing

2022-11-29 04:02 UTC, closed without merging

2022-12-06 18:10 UTC, himanshuapril1 commented
> This can be a breaking change.
> 
> Can we just add alias so `waitForTimeout` to be the same as `waitforTimeout` ?
> 
> Personally I would prefer to use waitForTimeout as it seems more native to me and less confusing

I agree on the same, however if adding alias makes sense then I'd go for that.