adding init UTs
Codeception/CodeceptJS pull request #3466
Opened 2022-10-21 15:27 UTC by PeterNgTr

## Motivation/Description of the PR
- Description of this PR, which problem it solves
- Resolves #issueId (if applicable).

Applicable helpers:

- [ ] WebDriver
- [ ] Puppeteer
- [ ] Nightmare
- [ ] REST
- [ ] FileHelper
- [ ] Appium
- [ ] Protractor
- [ ] TestCafe
- [ ] Playwright

Applicable plugins:

- [ ] allure
- [ ] autoDelay
- [ ] autoLogin
- [ ] customLocator
- [ ] pauseOnFail
- [ ] coverage
- [ ] retryFailedStep
- [ ] screenshotOnFail
- [ ] selenoid
- [ ] stepByStepReport
- [ ] stepTimeout
- [ ] wdio
- [ ] subtitles

## Type of change

- [ ] :fire: Breaking changes
- [ ] :rocket: New functionality
- [ ] :bug: Bug fix
- [ ] :clipboard: Documentation changes/updates
- [ ] :hotsprings: Hot fix
- [ ] :hammer: Markdown files fix - not related to source code
- [ ] :nail_care: Polish code

## Checklist:

- [ ] Tests have been added
- [ ] Documentation has been added (Run `npm run docs`)
- [ ] Lint checking (Run `npm run lint`)
- [ ] Local tests are passed (Run `npm test`)

2022-10-22 06:28 UTC, Arhell approved these changes

2022-10-24 09:51 UTC, DavertMik requested changes
Thank you so much, one only thing to improve here:

2022-10-24 09:51 UTC, DavertMik commented on package.json
> +    "inquirer-test": "^2.0.1",
can we move this to dev dependencies?

2022-10-24 10:59 UTC, DavertMik approved these changes
Thank you!

2022-10-24 10:59 UTC, merged