Added `DataTable` and `DataTableArgument` types
Codeception/CodeceptJS pull request #3492
Opened 2022-11-06 00:38 UTC by zaxoavoki

## Motivation/Description of the PR
- Added `DataTable` and `DataTableArgument` types to `index.d.ts`
- Resolves #2926 

## Type of change

- [ ] :fire: Breaking changes
- [ ] :rocket: New functionality
- [ ] :bug: Bug fix
- [x] :clipboard: Documentation changes/updates
- [ ] :hotsprings: Hot fix
- [ ] :hammer: Markdown files fix - not related to source code
- [ ] :nail_care: Polish code

## Checklist:

- [x] Lint checking (Run `npm run lint`)
- [x] Local tests are passed (Run `npm test`)

2022-11-06 00:39 UTC, zaxoavoki commented
Hey, could you please review my changes and tell me if you need something more?

2022-11-07 00:19 UTC, Arhell reviewed
cc @DavertMik

2022-11-25 19:12 UTC, DavertMik requested changes
This typings are too strict

2022-11-25 19:12 UTC, DavertMik commented on lib/data/table.js
>    constructor(array) {
I'm not sure this is correct
As you can actually pass any array into DataTable
DataTableArgument works only with Gherkin tables while DataTable works with classical tables as well

2022-11-25 19:12 UTC, closed without merging

2022-11-25 19:14 UTC, DavertMik commented
I'm sorry it took me that long to review this PR,
I could not get a free time as due to constant missile attacks from russia I had power & internet glitches, as well as extra work on my main product Testomat.io.