fix: cannot load wdio helper
Codeception/CodeceptJS pull request #3578
Opened 2023-02-07 06:15 UTC by PeterNgTr

## Motivation/Description of the PR
- fix: cannot load wdio helper

Applicable helpers:

- [ ] WebDriver

## Type of change
- [ ] :bug: Bug fix

## Checklist:

- [ ] Tests have been added
- [ ] Documentation has been added (Run `npm run docs`)
- [ ] Lint checking (Run `npm run lint`)
- [ ] Local tests are passed (Run `npm test`)

2023-02-08 01:24 UTC, Arhell approved these changes

2023-02-08 15:47 UTC, DavertMik approved these changes

2023-02-08 15:51 UTC, DavertMik requested changes
I think we use `version ` only to check if it is webdriverio v5
If the actual version is 8 I don't think we have to support v5 in any way

So I would remove all the code assumed of v5 usage and version detection as well

2023-02-09 05:34 UTC, PeterNgTr commented
> I think we use `version ` only to check if it is webdriverio v5 If the actual version is 8 I don't think we have to support v5 in any way
> 
> So I would remove all the code assumed of v5 usage and version detection as well

updated.

2023-02-12 21:39 UTC, DavertMik approved these changes

2023-02-12 21:40 UTC, merged