fix: handle importing custom helper nicely
Codeception/CodeceptJS pull request #3691
Opened 2023-06-07 06:36 UTC by kobenguyent

## Motivation/Description of the PR
- This PR aims to handle the importing helpers nicely.

````
// new export syntax

class CustomHelper {}

export default CustomHelper;

// old export syntax

class CustomHelper {}

export = CustomHelper;

// js class
class TestHelper extends Helper {

}

module.exports = TestHelper;

````

## Type of change
- [x] :bug: Bug fix

## Checklist:

- [ ] Tests have been added
- [ ] Documentation has been added (Run `npm run docs`)
- [ ] Lint checking (Run `npm run lint`)
- [ ] Local tests are passed (Run `npm test`)

2023-06-07 14:06 UTC, EgorBodnar commented on lib/container.js
> +      // @ts-ignore
Could we avoid of the `// @ts-ignore` by something like this: 

```js
const getModule = (moduleName) => {
  const module = require(moduleName);
  return module.default ? module : { default: module };
};

const isHelperModule = moduleName.startsWith('./helper/');

const HelperClass = isHelperModule
  ? require(moduleName)
  : getModule(moduleName).default;

```

?

2023-06-07 14:15 UTC, kobenguyent commented on lib/container.js
> +      // @ts-ignore
![Screenshot 2023-06-07 at 16 14 41](https://github.com/codeceptjs/CodeceptJS/assets/7845001/b6355ba9-f282-4ccf-b7c8-4acaec8002d1)
it doesn't resolves the issue unfortunately.

2023-06-07 14:35 UTC, EgorBodnar commented on lib/container.js
> +      // @ts-ignore
Oh... I see. Hard situation.

A good time to think about switching to TypeScript and solve the typing issue the correct way :slightly_smiling_face:

2023-06-07 14:35 UTC, EgorBodnar approved these changes

2023-06-08 22:14 UTC, DavertMik commented
Sorry, I can't see purpose of this

`export default` looks nicer, indeed. But as we still use it through require() I don't see any point of it
It might confuse users as they may think that they can use `import` inside CodeceptJS which is not true

Moving away from CommonJS would be a nice idea but I see that it requires a lot of time, especially as we have dynamic imports everywhere.

2023-06-09 03:44 UTC, kobenguyent commented
Hey @DavertMik, I wanted to discuss a change regarding how we handle the loading of custom helpers. Nowadays, most users are using TypeScript for their custom helpers, and the "export =" syntax, which is deprecated, is being replaced with "export default" to export classes. However, this change causes errors when users try to do the same with CodeceptJS. This pull request aims to address this issue by ensuring that any syntax used to export classes in custom helpers will not cause any problems. By doing so, we won't limit users in their custom helper choices. Of course, it's important to note that their custom helpers will remain their responsibility, but our core functionality will continue to work flawlessly. This change could be a way to attract more users.

2023-07-01 23:22 UTC, DavertMik requested changes
OK, I'm convinced to accept this
But please do a minor change to improve the code readability

2023-07-01 23:22 UTC, DavertMik commented on lib/container.js
> +      const HelperClass = moduleName.startsWith('./helper/') ? require(moduleName) : require(moduleName).default || require(moduleName);
Could we split this into multiple operators as this becomes unreadable and it's hard to understand which operator is used in which context

2023-07-02 08:41 UTC, merged