fix: file name is not unique enough when running tests in parallel
Codeception/CodeceptJS pull request #3697
Opened 2023-06-09 15:17 UTC by kobenguyent

## Motivation/Description of the PR
- The fileName is not unique when running tests in parallel and it leads to the issue that attachment couldn't attach to allure report.

Applicable helpers:
- [ ] Playwright

## Type of change
- [ ] :bug: Bug fix

## Checklist:

- [ ] Tests have been added
- [ ] Documentation has been added (Run `npm run docs`)
- [ ] Lint checking (Run `npm run lint`)
- [ ] Local tests are passed (Run `npm test`)

2023-06-10 04:25 UTC, EgorBodnar commented
a good fix, as a result of our discussion :raised_hands:

2023-06-10 04:43 UTC, EgorBodnar commented on lib/helper/Playwright.js
> +  const fileName = `${`${global.output_dir}${pathSeparator}trace${pathSeparator}${makeId(20)}_${clearString(name)}`.slice(0, 245)}.zip`;
is the fileName unique for one test or it probably should be unique within one test step too?

* If it should be unique per test, use `mocha current test id`

* If it should uniq  within one test use already installed CodeceptJS dependency - `uuid` tp generate really unique id

2023-06-10 04:57 UTC, EgorBodnar requested changes
Should the `fileName` be unique for one test or it probably should be unique within one test step too?

* If it should be unique per test, use `mocha current test id` or `nodejs worker.threadId`

* If it should be unique within one test use already installed CodeceptJS dependency - `uuid` to generate really unique id. 

So better to delete the new `function makeId(length) {}`

2023-06-10 07:43 UTC, kobenguyent commented
> Should the `fileName` be unique for one test or it probably should be unique within one test step too?
> 
> * If it should be unique per test, use `mocha current test id` or `nodejs worker.threadId`
> * If it should be unique within one test use already installed CodeceptJS dependency - `uuid` to generate really unique id.
> 
> So better to delete the new `function makeId(length) {}`

updated per CR. Thanks for pointing it out!

2023-06-11 00:34 UTC, EgorBodnar approved these changes

2023-06-23 00:28 UTC, Arhell approved these changes

2023-06-23 03:35 UTC, merged